In [1]:
from pyspoc import Calculator, Config

Starting JVM with java class /Users/joshparchure/Documents/pyspocClone24Jun/py-spoc/pyspoc/lib/jidt/infodynamics.jar.
Jpype JVM not available: [Errno 2] JVM DLL not found: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

In [ ]:
from pathlib import Path
import os
import numpy as np
import pandas as pd
project_root = Path('./').resolve().parents[2]

In [3]:
new_mod_path = os.path.join(project_root,'hjResearch_2025','summary_stats','distance_distrib_stats.py')
print(new_mod_path)

/Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py

Here we will run some ReducedStatistics on some synthetic datasets which were generated according to some random linear SCM on the "chain" and "loop" structured DAGs.

---
## Running reduced statistics
### 1) Euclidean distances; estimating number of peaks with KDE

In [4]:
my_config_yaml = f"""
ReducedStatistics:
  {new_mod_path}:
    DistanceDistributionModesSummarize:
      schemes:
        scheme_1:
          metric: euclidean
          point: global_mean_centroid
          type: kde
"""
my_config_name = "new_config"
cfg = Config.from_yaml(my_config_name, my_config_yaml)

Registering YAML string.
Building internal configuration.
/Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py
    ✔ ReducedStatistic DistanceDistributionModesSummarize scheme 'scheme_1' added successfully.

In [5]:
def process_motivation_dag(dag_number, project_root):

    base_dir = os.path.join(project_root, 'mastersResearch_Jun_Sept2025', 'causalDiscovery_J', 'motivationAnalysis')
    meta_file = os.path.join(base_dir, f'motivation_dag_{dag_number}.csv')
    
    print(f"--- Processing motivation_dag_{dag_number}.csv ---")
    meta_df = pd.read_csv(meta_file)
    display(meta_df)

    calc = Calculator(meta_df)
    calc.compute(cfg)
    results = calc.results
    print(results)

process_motivation_dag(1, project_root)
process_motivation_dag(2, project_root)

--- Processing motivation_dag_1.csv ---

           V0        V1        V2
0   -1.309975 -0.210383 -0.561118
1   -0.286121 -1.210426 -1.000506
2   -0.338890 -0.660613 -0.724111
3   -0.372171 -0.032225 -0.151854
4   -0.166640 -0.283169 -0.177887
..        ...       ...       ...
995  1.542328  0.405907  0.674028
996  0.502690  1.449731  1.260039
997  0.300818  1.296965  1.185995
998 -0.332102 -1.175522 -0.875340
999  0.998632  0.685157  0.859886

[1000 rows x 3 columns]

Normalising the dataset...

Processing [None: /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionModesSummarize.scheme_1]: 100%|██████████| 1/1 [00:00<00:00, 90.31it/s]

Calculation complete. Time taken: 0.0117s
Statistic /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionModesSummarize.scheme_1
Reducer                                                                                                                                                               self
0                                                        2.0
--- Processing motivation_dag_2.csv ---

           V0        V1        V2
0   -0.232403 -0.391251 -0.270432
1    0.276521  0.266542  0.311923
2   -0.160806 -0.093603  0.021258
3   -0.174242 -0.221482 -0.329510
4   -0.186991 -0.097720 -0.329971
..        ...       ...       ...
995 -1.863905 -1.773036 -1.395144
996 -1.611131 -1.434023 -1.679805
997 -1.720087 -1.215960 -1.793412
998 -1.320740 -1.161177 -1.474408
999 -1.606012 -1.598749 -1.791309

[1000 rows x 3 columns]

Normalising the dataset...

Processing [None: /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionModesSummarize.scheme_1]: 100%|██████████| 1/1 [00:00<00:00, 137.82it/s]

Calculation complete. Time taken: 0.0078s
Statistic /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionModesSummarize.scheme_1
Reducer                                                                                                                                                               self
0                                                        2.0